### ISSUE TITLE
Configure CM in compose

### ISSUE THREAD

**Issue by Tyson1986** [aerokube/cm#314]
Hi. We try to run Selenoid via docker-compose. Everything works fine, but we'd like to use our private registry as a mirror for docker hub. Based on the doc https://aerokube.com/cm/latest/ I see that it is possible to do via --registry flag.
The problem is that I can't find how to do it via compose file. We have the following compose:
```
selenoid:
    image: "aerokube/selenoid:latest"
    network_mode: bridge
    volumes:
      - "$PWD:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/opc/selenoid/videos:/opt/selenoid/videos"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/home/opc/selenoid/videos
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/videos", "-session-attempt-timeout", "2m", "-service-startup-timeout", "2m"]
    ports:
      - "4444:4444"
```
If add "--registry", "https://my.registry.com" in command, Selenoid can't parse config and fail to start.
In the Internet I haven't found any example of how can I add CM configs, only CLI flags are described here:
https://github.com/aerokube/selenoid/blob/master/docs/cli-flags.adoc

How can I add --registry to docker-compose.yml?

**Comment by Tyson1986** [comment]
As I see there is no CM inside "aerokube/selenoid" image:
https://github.com/aerokube/selenoid/blob/master/Dockerfile#L7
Is there some image that starts selenoid via CM? Or should I create some for my self? Like:
```
FROM aerokube/selenoid

ENTRYPOINT["./cm", "selenoid", "start", "--vnc", "--registry", "https://my.registry.com/"]
```
Is this the correct way?

**Comment by Tyson1986** [comment]
I hoped that there is a single point. But it also work. Thanks. I'm aware about browser images and
```
video-recorder-image string
    Image to use as video recorder (default "selenoid/video-recorder")
```
Is there any other place where I should update images?

**Comment by vania-pooh** [comment]
@Tyson1986 these two should be sufficient.

**Comment by Tyson1986** [comment]
I see following logs:
```
selenoid_1_7b216e1867d6 | 2022/02/21 13:04:31 [5] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
selenoid_1_7b216e1867d6 | 2022/02/21 13:04:31 [5] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [d553d3b111d6f8c27cd98005f0fbae53521449d7f8aac96dc50ed5a256ebc028]
selenoid_1_7b216e1867d6 | 2022/02/21 13:04:32 [5] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [d553d3b111d6f8c27cd98005f0fbae53521449d7f8aac96dc50ed5a256ebc028] [0.32s]
selenoid_1_7b216e1867d6 | 2022/02/21 13:04:32 [5] [SERVICE_STARTED] [my-registry.example.com/selenoid/chrome] [f4f82c044b6eb939f0b47ce991298eb34d9a48a3213058d9dc7d2ef1cb59b707] [0.21s]
```

My compose is:
```yml
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest"
    network_mode: bridge
    volumes:
      - "$PWD:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/opc/selenoid/video:/opt/selenoid/video"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
    command: -session-attempt-timeout 2m -service-startup-timeout 2m -capture-driver-logs true -video-recorder-image my-registry.example.com/selenoid/video-recorder:latest-release -log-output-dir /opt/selenoid/logs -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video
    ports:
      - "4444:4444"
```

Browser images are defined in browsers.json works fine (you can see it in logs as my-registry.example.com/selenoid/chrome)
But logs show selenoid/video-recorder instead of my-registry.example.com/selenoid/video-recorder
Is my "command" section in compose correct?
